# Generated by Django 3.0.10 on 2020-09-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shawtier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(),
        ),
    ]
